In [1]:
import numpy as np

In [2]:
data = np.load('monthdata.npz')
totals = data['totals']
counts = data['counts']

In [3]:
print(totals)
print(counts)

[[1809 1482 2159  374  606  428  442   68  956 1429 1349 1846]
 [ 121   22   46   40  683  616 2061  834  253  276   27  224]
 [ 896 1232  992 1106 1236 1015 1264 1096 1026 2422 1184 1099]
 [1491 1473 1452 1595 1001  725  734  445  845 2185 1305 1835]
 [ 930  561  533  204  546  748  662  274  785 1620 1293  295]
 [ 183  982  621  471  667  671  525 1599  433 1176  594  627]
 [ 363  491  729  681  346  269  399  667  663  452  497  821]
 [1682 1304 1616  242  516  582  328  138  784 2034 2402 1520]
 [ 220   90   28  120   98  306  154  280  488  158  176  116]]
[[30 22 30 30 21 21 20 25 20 19 17 16]
 [31 29 31 30 31 30 31 30 30 30 30 30]
 [31 29 31 30 30 30 31 31 30 31 30 31]
 [31 29 31 30 31 30 31 31 29 30 30 31]
 [31 29 31 29 31 29 30 31 30 31 30 29]
 [31 29 31 30 31 30 28 31 30 30 29 31]
 [31 28 31 30 31 30 31 31 30 31 29 31]
 [30 28 31 30 30 29 30 31 30 31 30 30]
 [31 28 31 30 31 30 31 31 30 30 30 30]]


In [4]:
year_total = totals.sum(axis=1)
year_total

array([12948,  5203, 14568, 15086,  8451,  8549,  6378, 13148,  2234],
      dtype=int64)

In [5]:
lowest_year_total_index = year_total.argmin()
lowest_year_total_index #Answer for question 1

8

In [6]:
all_locations_month_total = totals.sum(axis=0)
all_locations_month_total

array([ 7695,  7637,  8176,  4833,  5699,  5360,  6569,  5401,  6233,
       11752,  8827,  8383], dtype=int64)

In [7]:
all_locations_observe_count = counts.sum(axis=0)
all_locations_observe_count

array([277, 251, 278, 269, 267, 259, 263, 272, 259, 263, 255, 259],
      dtype=int64)

In [8]:
all_locations_average_precipitation = all_locations_month_total/all_locations_observe_count

In [9]:
all_locations_average_precipitation #Answer for question 2

array([27.77978339, 30.42629482, 29.41007194, 17.96654275, 21.34456929,
       20.69498069, 24.97718631, 19.85661765, 24.06563707, 44.68441065,
       34.61568627, 32.36679537])

In [11]:
counts_total = counts.sum(axis=1)
counts_total

array([271, 363, 365, 364, 361, 361, 364, 360, 363], dtype=int64)

In [12]:
city_average_presi = year_total / counts_total
city_average_presi #Answer for question 3

array([47.77859779, 14.33333333, 39.91232877, 41.44505495, 23.4099723 ,
       23.68144044, 17.52197802, 36.52222222,  6.15426997])

In [18]:
reshaped_totals = totals.reshape(9,4,3)
reshaped_totals

array([[[1809, 1482, 2159],
        [ 374,  606,  428],
        [ 442,   68,  956],
        [1429, 1349, 1846]],

       [[ 121,   22,   46],
        [  40,  683,  616],
        [2061,  834,  253],
        [ 276,   27,  224]],

       [[ 896, 1232,  992],
        [1106, 1236, 1015],
        [1264, 1096, 1026],
        [2422, 1184, 1099]],

       [[1491, 1473, 1452],
        [1595, 1001,  725],
        [ 734,  445,  845],
        [2185, 1305, 1835]],

       [[ 930,  561,  533],
        [ 204,  546,  748],
        [ 662,  274,  785],
        [1620, 1293,  295]],

       [[ 183,  982,  621],
        [ 471,  667,  671],
        [ 525, 1599,  433],
        [1176,  594,  627]],

       [[ 363,  491,  729],
        [ 681,  346,  269],
        [ 399,  667,  663],
        [ 452,  497,  821]],

       [[1682, 1304, 1616],
        [ 242,  516,  582],
        [ 328,  138,  784],
        [2034, 2402, 1520]],

       [[ 220,   90,   28],
        [ 120,   98,  306],
        [ 154,  280,  488],
    

In [23]:
reshaped_totals_sum = reshaped_totals.sum(axis=2)
reshaped_totals_sum #Answer for question 4

array([[5450, 1408, 1466, 4624],
       [ 189, 1339, 3148,  527],
       [3120, 3357, 3386, 4705],
       [4416, 3321, 2024, 5325],
       [2024, 1498, 1721, 3208],
       [1786, 1809, 2557, 2397],
       [1583, 1296, 1729, 1770],
       [4602, 1340, 1250, 5956],
       [ 338,  524,  922,  450]], dtype=int64)